# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flareduct < Formula
  desc "CLI wrapper around cloudflared for Cloudflare Tunnel workflows"
  homepage "https://github.com/ZatTwilight/flareduct"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ZatTwilight/flareduct/releases/download/v0.1.2/flareduct_0.1.2_Darwin_x86_64.tar.gz"
      sha256 "884520ba054358232c35ec33f3e3cc5712f47c592e1c2703d847a535f04d7eb8"

      define_method(:install) do
        bin.install "flareduct"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ZatTwilight/flareduct/releases/download/v0.1.2/flareduct_0.1.2_Darwin_arm64.tar.gz"
      sha256 "bb375caee83370bca3a1bcc702c5811f9f2c8f37205170117e2e8ca0efccef13"

      define_method(:install) do
        bin.install "flareduct"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ZatTwilight/flareduct/releases/download/v0.1.2/flareduct_0.1.2_Linux_x86_64.tar.gz"
      sha256 "757544b222bf0aa20e16e1435a9bffc1a21943f8e59b9776ee91164755f42448"
      define_method(:install) do
        bin.install "flareduct"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ZatTwilight/flareduct/releases/download/v0.1.2/flareduct_0.1.2_Linux_arm64.tar.gz"
      sha256 "739297575f682e1f21d8d17f062496d46da75cc3979ab58de5d2da4109738b74"
      define_method(:install) do
        bin.install "flareduct"
      end
    end
  end

  test do
    system "#{bin}/flareduct", "version"
  end
end
