# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flareduct < Formula
  desc "CLI wrapper around cloudflared for Cloudflare Tunnel workflows"
  homepage "https://github.com/ZatTwilight/flareduct"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ZatTwilight/flareduct/releases/download/v0.1.1/flareduct_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "7fcd8b2f1150473a27ff2811aac0c0c59181f62bb77cbfa28acec4002caff894"

      define_method(:install) do
        bin.install "flareduct"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ZatTwilight/flareduct/releases/download/v0.1.1/flareduct_0.1.1_Darwin_arm64.tar.gz"
      sha256 "180c905744d164b3570cc2408445562e78c95ce7e710b8f7a9159757ced709ca"

      define_method(:install) do
        bin.install "flareduct"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ZatTwilight/flareduct/releases/download/v0.1.1/flareduct_0.1.1_Linux_x86_64.tar.gz"
      sha256 "4e6d09b9371ff5d11fc9c28cbfd8d42f6f6cb8c5ffcd87f28307774ed2f14f2b"
      define_method(:install) do
        bin.install "flareduct"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ZatTwilight/flareduct/releases/download/v0.1.1/flareduct_0.1.1_Linux_arm64.tar.gz"
      sha256 "11ffd44dd0dba38ce3aa08427da296b9831f6d1c1bab39bd9d4523cdc31d342e"
      define_method(:install) do
        bin.install "flareduct"
      end
    end
  end

  test do
    system "#{bin}/flareduct", "version"
  end
end
