# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flareduct < Formula
  desc "CLI wrapper around cloudflared for Cloudflare Tunnel workflows"
  homepage "https://github.com/ZatTwilight/flareduct"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ZatTwilight/flareduct/releases/download/v0.1.0/flareduct_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "19e9deaa5ea7b046945848ea6ea9237fd7bb1cd5c8677fbcf6bfeada03424a8d"

      define_method(:install) do
        bin.install "flareduct"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ZatTwilight/flareduct/releases/download/v0.1.0/flareduct_0.1.0_Darwin_arm64.tar.gz"
      sha256 "69633a5726a806e1156923c34869acebedecec74f0368a1fe1918547a6b65b2d"

      define_method(:install) do
        bin.install "flareduct"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ZatTwilight/flareduct/releases/download/v0.1.0/flareduct_0.1.0_Linux_x86_64.tar.gz"
      sha256 "56ff198b9abf9d75371d95cbfd72632364a5053e707657a649717df7a9234552"
      define_method(:install) do
        bin.install "flareduct"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ZatTwilight/flareduct/releases/download/v0.1.0/flareduct_0.1.0_Linux_arm64.tar.gz"
      sha256 "8d341167cd0df459614893e06a4899c6f3a1a75ba8ab2d3f8f4abde70c5815a8"
      define_method(:install) do
        bin.install "flareduct"
      end
    end
  end

  test do
    system "#{bin}/flareduct", "version"
  end
end
